#!/bin/bash
pipeline {
    agent any
    environment {
        PATH = "C:\\WINDOWS\\SYSTEM32"
    }
    options 
    {
        skipStagesAfterUnstable()
    }
   
    stages 
    {
           stage('Step1')
        {
            steps
            {
            sh"""
                  bat "step1.bat"
            """
            }
        }           

}
}
