#!/bin/bash
pipeline {
    agent any
    environment {
        PATH = "C:\\WINDOWS\\SYSTEM32"
    }
    options 
    {
        skipStagesAfterUnstable()
    }
   
    stages 
    {
           stage('Step1')
        {
            steps
            {
                bat 'start cmd.exe /c C:\\Users\\josue.valencia\\.jenkins\\workspace\\Pipelines_123\\ScripPipeline\\step1.bat'
            }
        }
        
           stage('Step2')
        {
            steps
            {
                bat 'start cmd.exe /c C:\\Users\\josue.valencia\\.jenkins\\workspace\\Pipelines_123\\ScripPipeline\\step2.bat'
            }
        }
        
           stage('Step3')
        {   
        git add . 
        git commit -m "Commit"
        git remote add origin https://github.com/Josue-lab/Script-Example.git

}

}
}
